AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation template for creating a task definition"
Resources:
  MyTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      RequiresCompatibilities:
        - "FARGATE"
      ExecutionRoleArn: "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"
      Cpu: 512
      Memory: 1024
      NetworkMode: "awsvpc"
      ContainerDefinitions:
        - Name: "jenkins-slave"
          Image: "brunosantos88/jenkins-slave:latest"
          MemoryReservation: 256
          Memory: 512
          PortMappings:
            - ContainerPort: 8080
              Protocol: tcp